### PR TITLE
Update Mia-Platform position on the ecosystem

### PR DESCRIPTION
**Pull request by ugho16**
Updated Mia-Platform page changing its location and added Rönd in the security tool section

### CODE REVIEW

**Comment by FL303** [comment]
@ugho16 thanks for the update. I couldn't find any materials where Mia-Platform is described as a Platform Orchestrator. Sure this is the right category? If so, please share some examples (home page, docs, etc.). Thanks.

**Comment by ugho16** [comment]
Hi @FL303, we do not describe ourselves as a Platform Orchestrator but as a Platform Builder ([here](https://docs.mia-platform.eu/docs/overview/mia_platform_overview) you can find an example). Since there is no dedicated category for Platform Builders, Platform Orchestrator is the closest available definition among those on the website

**Comment by FL303** [comment]
@ugho16 Thanks for clarifying. This might be a bit confusing. Maybe create a separate category? The current description of the Platform Orchestrator might not work for you:
"Platform Orchestrators are the center piece of any dynamic Internal Developer Platform. A Platform Orchestrator enables dynamic configuration management and executes a declarative application model."
https://internaldeveloperplatform.org/platform-orchestrators/

**Comment by ugho16** [comment]
@FL303 Thanks for your reply. If that can work for you, I can rework this PR and create a dedicated category for Platform Builders.

**Comment by FL303** [comment]
@ugho16 I had another look at your website, and I have to admit I still struggle with what might be the right category. 
Your entire communication signals mia-platform is a PaaS (that also can be self-hosted): 
https://docs.mia-platform.eu/docs/overview/mia_platform_overview 
If Mia IS the platform, how can it be a platform builder simultaneously?
I also didn't find the term "Platform Builder" on your home page or in any other communication.
Imo this seems to be the right category: https://internaldeveloperplatform.org/paas-devops-platforms/

**Comment by ugho16** [comment]
Hi @FL303, I understand that there might be some confusion since we are realigning our assets to the value proposition, but I can assure you that we do exactly the same things that a Platform orchestrator does. We also provide a PaaS solution for small companies, but it's a small part of our business. 
If you need more clarification, we will be happy to schedule a call and provide you with more information.

**Comment by FL303** [comment]
@ugho16 I think this is really difficult because Mia's public materials don't use the term platform orchestrator, but also not dynamic configuration management (following the category definition):
https://internaldeveloperplatform.org/platform-orchestrators/
"Platform Orchestrators are the center piece of any dynamic Internal Developer Platform. A Platform Orchestrator enables dynamic configuration management and executes a declarative application model."
Compare this case with the portal category:
https://internaldeveloperplatform.org/developer-portals/
All the tools listed there claim themselves as portals, this is how it also works for all other categories.

**Pull request closed without merging**
