### PR TITLE
Add Choreo to the ecosystem

### PR DESCRIPTION
**Pull request by yashodgayashan**
Greetings from WSO2!

This PR adds Choreo to the list of developer platforms. 
Please let us know if anything needs to be adjusted. Thanks!

### CODE REVIEW

**Comment by binura-g** [comment]
Hi @FL303, just bringing this back up for your review :) Thanks!

**Review by FL303 — CHANGES_REQUESTED** [review]
Hi @yashodgayashan thanks for contributing! 
We are happy to add Chreo to the DevOps platform/PaaS section but would kindly request some minor changes:
Following the definition on this page an ["Internal Developer Platform (IDP)"](https://internaldeveloperplatform.org/what-is-an-internal-developer-platform/) refers to a platform built by platform engineering teams using various tools and technologies. To avoid confusion for visitors of this page, we recommend not using the term "Internal Developer Platform (IDevP)." Instead, please use "internal developer platform as a service" (as you already do on [WSO2 Choreo](https://wso2.com/choreo/)) or simply "PaaS."

**Comment by yashodgayashan** [comment]
Hi @FL303 thanks for the review. I have updated with your suggestions.

**Comment by FL303** [comment]
Thanks @yashodgayashan! Could you please update the claim too?

**Comment by yashodgayashan** [comment]
> Thanks @yashodgayashan! Could you please update the claim too?

Updated with the latest commit

**Review by FL303 — APPROVED** [review]

**Review by FL303 — APPROVED** [review]

**Comment by yashodgayashan** [comment]
Hi @christophcrichter could you please review this? :)

**Review by FL303 — APPROVED** [review]

**Review by christophcrichter — APPROVED** [review]
LGTM; thanks for contributing

**Pull request merged**
