### PR TITLE
Update configure8.md

### PR DESCRIPTION
**Pull request by jjmutron**

### CODE REVIEW

**Review by FL303 — COMMENTED** [review]
Hi @jjmutron , thanks for contributing. There is already an open PR, see my comment there: https://github.com/InternalDeveloperPlatform/public-site/pull/143

**Comment by jjmutron** [comment]
Hi Florian - this pr addresses your comments in 143. Matthew is on
vacation, so I've submitted this update for him.v Thanks

**Review by FL303 — APPROVED** [review]

**Comment by FL303** [comment]
@jjmutron thanks for letting me know, approved!

**Comment by jjmutron** [comment]
Thank you!!

**Review by christophcrichter — APPROVED** [review]
LGTM; thanks for contributing

**Pull request merged**
