### PR TITLE
Adding massdriver

### PR DESCRIPTION
**Pull request by coryodaniel**
Adding massdriver to platform tooling

### CODE REVIEW

**Comment by coryodaniel** [comment]
We do dynamic configuration via our visual connection system and have a declarative app model that supports extensions for pretty much any cloud runtime. We support about 10 out of the box, but have customers that are even running databricks workloads through it the model. 

Docs are current on functionality but our marketing copy may be a bit out of date on the docs landing page.

**Comment by coryodaniel** [comment]
@FL303 any update?

**Comment by FL303** [comment]
@coryodaniel thanks for following up and sorry for the radio silence. Please let us know once the docs is updated following Thoughtworks' definition, it is pretty accurate: https://www.thoughtworks.com/radar/techniques/platform-orchestration
We do not want to confuse the audience. It should be clear if Massdriver is one part of the Internal Developer Platform (e.g. a Platform Orchestrator), a portal, a PaaS or similar. At the moment not clear.

**Comment by coryodaniel** [comment]
Our docs are updated and I think it’s pretty clear.

**Comment by coryodaniel** [comment]
We tend not to use the word as it doesn't convert as well as describing what the platform does (build IDPs, manage app catalog in a declarative way), but if it takes literally using the word to get through the gatekeeping, you can see it [here](https://docs.massdriver.cloud/#:~:text=platform%20orchestrator) and [here](https://www.massdriver.cloud/#:~:text=platform%20orchestrator)

**Comment by FL303** [comment]
Thanks!

**Review by christophcrichter — APPROVED** [review]
LGTM; thanks

**Pull request merged**
