### PR TITLE
Added Dynatrace to monitoring

### PR DESCRIPTION
**Pull request by wlfghdr**

### CODE REVIEW

**Review by FL303 — CHANGES_REQUESTED** [review]
Hi @wlfghdr, thank you, please add a link to the overview page as well: https://internaldeveloperplatform.org/monitoring/

**Comment by christophcrichter** [comment]
@wlfghdr I made the changes that @FL303 suggested. Can you please check whether ok for you?

**Comment by wlfghdr** [comment]
added it also to security

**Comment by christophcrichter** [comment]
@FL303 Ok with you?

**Review by FL303 — APPROVED** [review]

**Review by christophcrichter — APPROVED** [review]
Approved

**Pull request merged**
