### PR TITLE
Add Nitric framework to platform-orchestration

### PR DESCRIPTION
**Pull request by raksiv**

### CODE REVIEW

**Comment by christophcrichter** [comment]
@raksiv thanks for the contribution. I was checking your docs but I couldn't find any reference to Nitric being a Platform Orchestrator. Are you sure that this is the right category? If so, please share some examples that explain the Platform Orchestrator functionality (e.g., homepage, tutorials). Thanks.

**Comment by raksiv** [comment]
@christophcrichter sure, no worries - I did not find a good match in the categories. Perhaps this should've been a question upfront. Hopefully you can help us find a better fit.

The Nitric framework allows developers to self-service their infrastructure requirements by requesting their resources directly in code. We have written out of box providers which fulfill the request using Terraform and Pulumi, which is our opinion on how the resources should be provisioned, however, platform engineers are also able to extend these providers to provision infrastructure the way they want.. using the IaC tool of choice.

**Comment by christophcrichter** [comment]
@raksiv no problem at all. IDPs still are an emerging category without a strict terminology.

@FL303 what do you think would fit as a category?

**Comment by raksiv** [comment]
@christophcrichter @FL303 what do you think about a new category e.g. along lines of "self-service infrastructure".

**Comment by raksiv** [comment]
@FL303 Thanks for the thoughtful response, no worries about the timeline - I think thats actually a very good suggestion. If you're good with it, I'll make changes to the PR to point it to this directory.

**Comment by raksiv** [comment]
Thanks, I reverted the original content and pushed an update with an index page.
Please feel free to modify if you feel any changes are required.

**Review by christophcrichter — APPROVED** [review]
LGTM; thanks for contributing and for adjusting

**Pull request merged**
