### PR TITLE
Add LiveWyer consultancy

### PR DESCRIPTION
**Pull request by waltlenu**
Hello,

Kindly requesting to add LiveWyer to the list of consultancies.

Thank you.

### CODE REVIEW

**Review by FL303 — COMMENTED** [review]
Thanks for contributing @waltlenu! Would you mind removing the marketing backlinks? Happy to add the profile.

**Comment by waltlenu** [comment]
I've removed the backlinks in https://github.com/InternalDeveloperPlatform/public-site/pull/193/commits/2497051617f52dd713f9c34e240849b86a9bfe57 

Thank you for reviewing @FL303 !

**Review by FL303 — APPROVED** [review]
Thanks!

**Review by FL303 — DISMISSED** [review]

**Comment by waltlenu** [comment]
@FL303 Thank you for approving! 

I noticed a conflict that prevented the merge, so I resolved it in https://github.com/InternalDeveloperPlatform/public-site/pull/193/commits/54cb32466432a7562d2eaa78ca7169892a542c99

Hope this helps!

**Review by FL303 — APPROVED** [review]

**Comment by FL303** [comment]
Thanks @waltlenu!

**Pull request merged**
